### ISSUE TITLE
K8S

### ISSUE THREAD

**Issue by rainit2006** [rainit2006/My_AWS-Cloud#26]

**Comment by rainit2006** [comment]
-------

**Comment by rainit2006** [comment]
在线练习：https://www.katacoda.com/courses/kubernetes/launch-single-node-cluster

**Comment by rainit2006** [comment]
##教材
https://www.gitbook.com/download/pdf/book/feisky/kubernetes

##核心组件
- etcd 保存了整个集群的状态；基本的 key-value 存储；
- apiserver 提供了资源操作的唯一入口，并提供认证、授权、访问控制、API 注册和发现等机制；
- controller manager 负责维护集群的状态，比如故障检测、自动扩展、滚动更新等；
- scheduler 负责资源的调度，按照预定的调度策略将 Pod 调度到相应的机器上；
- kubelet 负责维护容器的生命周期，同时也负责 Volume（CVI）和网络（CNI）的管理；
- Container runtime 负责镜像管理以及 Pod 和容器的真正运行（CRI）；
- kube-proxy 负责为 Service 提供 cluster 内部的服务发现和负载均衡
![image](https://user-images.githubusercontent.com/12871721/72661782-ee9fc000-3a21-11ea-99fd-0bbcd001639b.png)

## Basic
### Pod
Pod 是一组紧密关联的容器集合，它们共享 PID、IPC、Network 和 UTS namespace，是 Kubernetes 调度的基本单位。Pod 内的多个容器共享网络和文件系统，可以通过进程间通信和文件共享这种简单高效的方式组合完成服务。

###Node
Node 是 Pod 真正运行的主机，可以是物理机，也可以是虚拟机。为了管理 Pod，每个Node 节点上至少要运行 container runtime（比如 docker 或者 rkt）、 kubelet 和kube-proxy 服务。

### Namespace

### Server
通过 labels 为应用提供负载均衡和服务发现。匹配 labels的 Pod IP 和端口列表组成 endpoints，由 kube-proxy 负责将服务 IP 负载均衡到这些endpoints 上。
每个 Service 都会自动分配一个 cluster IP（仅在集群内部可访问的虚拟地址）和 DNS名，其他容器可以通过该地址或 DNS 来访问服务，而不需要了解后端容器的运行。

### Label
key/value 的方式。

### Annotations
Annotations 是 key/value 形式附加于对象的注解。

### 常见命令
- kubectl run ： 创建一个pod。其实kubectl run 并不是直接创建一个 Pod，而是先创建一个 Deployment 资
源（replicas=1），再由与 Deployment 关联的 ReplicaSet 来自动创建 Pod.
- kubectl get - 类似于 docker ps ，查询资源列表。（ex. kubectl get pods）
- kubectl describe - 类似于 docker inspect ，获取资源的详细信息
- kubectl logs - 类似于 docker logs ，获取容器的日志
- kubectl exec - 类似于 docker exec ，在容器内执行一个命令. (ex. $ kubectl exec nginx-app-4028413181-cnt1i ps aux)

### 使用 yaml 定义 Pod
在 Kubernetes 中，更经常使用 yaml 文件来定义资源，并通过 kubectl create -f file.yaml 来创建资源.

### 使用 Volume
Pod 的生命周期通常比较短，只要出现了异常，就会创建一个新的 Pod 来代替它。那容器产生的数据呢？容器内的数据会随着 Pod 消亡而自动消失。Volume 就是为了持久化容器数据而生。
比如可以为 redis 容器指定一个 hostPath 来存储 redis 数据。

### 使用 Service
前面虽然创建了 Pod，但是在 kubernetes 中，Pod 的 IP 地址会随着 Pod 的重启而变化，并不建议直接拿 Pod 的 IP 来交互。那如何来访问这些 Pod 提供的服务呢？使用Service。
Service 为一组 Pod（通过 labels 来选择）提供一个统一的入口，并为它们提供负载均衡和自动服务发现。

## 扩展应用
### 通过修改 Deployment 中副本的数量（replicas），可以动态扩展或收缩应用。
这些自动扩展的容器会自动加入到 service 中，而收缩回收的容器也会自动从 service 中删除。
![image](https://user-images.githubusercontent.com/12871721/72662019-eac16d00-3a24-11ea-950a-cade383c03f5.png)

### 滚动升级（Rolling Update）
通过逐个容器替代升级的方式来实现无中断的服务升级。
`kubectl rolling-update frontend-v1 frontend-v2 --image=image:v2`

在滚动升级的过程中，如果发现了失败或者配置错误，还可以随时回滚。
`kubectl rolling-update frontend-v1 frontend-v2 --rollback`

### 资源限制
Kubernetes 通过 cgroups 提供容器资源管理的功能，可以限制每个容器的 CPU 和内存使用。

### 健康检查
Kubernetes 作为一个面向应用的集群管理工具，需要确保容器在部署后确实处在正常的运行状态。Kubernetes 提供了两种探针（Probe，支持 exec、tcpSocket 和 http 方式）来探测容器的状态：
- LivenessProbe：探测应用是否处于健康状态，如果不健康则删除并重新创建容器
- ReadinessProbe：探测应用是否启动完成并且处于正常服务状态，如果不正常则不会接收来自 Kubernetes Service 的流量。
对于已经部署的 deployment，可以通过 kubectl edit deployment/nginx-app 来更新 manifest，增加健康检查部分。

## 集群联邦
集群联邦（Federation）用于跨可用区的 Kubernetes 集群，需要配合云服务商（如GCE、AWS）一起实现。
![image](https://user-images.githubusercontent.com/12871721/72664354-19007600-3a40-11ea-96ab-c52cdd34828a.png)

### 创建 Kubernetes 集群
创建 Kubernetes cluster（单机版）最简单的方法是 minikube。

**Comment by rainit2006** [comment]
## 实践
### 资源控制
推荐在 YAML 清单中针对所有 pod 设置 pod 请求和限制：
- pod 请求定义 pod 所需的 CPU 和内存量。Kubernetes 基于这些请求量进行节点调度。
- pod 限制是 pod 可以使用的最大 CPU 和内存量，用于防治失控 Pod 占用过多资源。

### 使用 kube-advisor 检查应用程序问题
你可以定期运行 kube-advisor 工具，检查应用程序的配置是否存在问题。

### Kubernetes HA
Kubernetes 从 1.5 开始，通过 kops 或者 kube-up.sh 部署的集群会自动部署一个高可用的系统，包括
- Etcd 集群模式
- kube-apiserver 负载均衡
- kube-controller-manager、kube-scheduler 和 cluster-autoscaler 自动选主（有且仅有一个运行实例）
![image](https://user-images.githubusercontent.com/12871721/72664570-05a2da00-3a43-11ea-99d0-9aba230a400b.png)

### Etcd 集群
1. 安装 cfssl
2. 生成 CA certs:
3. 生成 etcd server/peer certs
4. 最后运行 etcd，将如下的 yaml 配置写入每台 etcd 节点的/etc/kubernetes/manifests/etcd.yaml 文件中 
### kube-apiserver
1. 把 kube-apiserver.yaml 放到每台 Master 节点的/etc/kubernetes/manifests/ ，并把相关的配置放到/srv/kubernetes/ ，即可由 kubelet 自动创建并启动 apiserver
### kube-controller-manager 和 kube-scheduler
kube-controller manager 和 kube-scheduler 需要保证任何时刻都只有一个实例运行，需要一个选主的过程，所以在启动时要设置 --leader-elect=true 。
### kube-dns
kube-dns 可以通过 Deployment 的方式来部署，默认 kubeadm 会自动创建。但在大规模集群的时候，需要放宽资源限制。
### kube-proxy
默认 kube-proxy 使用 iptables 来为 Service 作负载均衡，这在大规模时会产生很大的Latency，可以考虑使用 IPVS 的替代方式。

### 数据持久化
除了上面提到的这些配置，持久化存储也是高可用 Kubernetes 集群所必须的。
对于公有云上部署的集群，可以考虑使用云平台提供的持久化存储，比如 aws ebs或者 gce persistent disk
对于物理机部署的集群，可以考虑使用 iSCSI、NFS、Gluster 或者 Ceph 等网络存储，也可以使用 RAID。

**Comment by rainit2006** [comment]
**minikube**
https://github.com/kubernetes/minikube
minikube implements a local Kubernetes cluster on macOS, Linux, and Windows. minikube's primary goals are to be the best tool for local Kubernetes application development and to support all Kubernetes features that fit.

Minikubeでは仮想化ソフトウェアを使ってLinuxがインストールされた仮想マシンを作成し、そこでKubernetesクラスタを動作させる仕組みになっている。そのため、仮想化ソフトウェアさえ用意すればWindowsやmacOS上でも利用できる。

**Comment by rainit2006** [comment]
Kubernetes v1.10 クラスタをVagrantで構築したメモ
https://qiita.com/MahoTakara/items/28cd766d0447140b7ae3

在线学习的，注册个账号。可以玩就2个节点的集群，但是这个集群有时间限制的，4个小时。
https://labs.play-with-k8s.com/

**Comment by rainit2006** [comment]
视频：
https://www.youtube.com/watch?v=W4XwsYs0h74&list=PLOfJyn_hHwP8sWcSwu7n3AcYuVVkVKSOt&index=5

**Comment by rainit2006** [comment]
一. k8s基本操作命令：
创建：kubectl create -f xxx.yaml
查询：kubectl get pod yourPodName， kubectl describe pod yourPodName
删除：kubectl delete pod yourPodName
更新：kubectl replace /path/to/yourNewYaml.yaml

二. 创建 pod 资源对象的yaml文件
```
apiVersion: v1
kind: Pod
metadata:
  name: kube100-site
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80
    - name: flaskapp-demo
      image: jcdemo/flaskapp
      ports:
        - containerPort: 5000
```
- apiVersion：此处值是v1，这个版本号需要根据安装的Kubernetes版本和资源类型进行变化，记住不是写死的。
- kind：此处创建的是Pod，根据实际情况，此处资源类型可以是Deployment、Job、Ingress、Service等。
- metadata：包含Pod的一些meta信息，比如名称、namespace、标签等信息。
- spe：包括一些container，storage，volume以及其他Kubernetes需要的参数，以及诸如是否在容器失败时重新启动容器的属性。可在特定Kubernetes API找到完整的Kubernetes Pod的属性。下面是一个典型的容器的定义：
```
spec:
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80
```
上述例子只是一个简单的最小定义：一个名字（front-end）、基于nginx的镜像，以及容器将会监听的指定端口号（80）。

将上面创建Pod的YAML文件保存成pod.yaml，然后使用Kubectl创建Pod：
```
$ kubectl create -f pod.yaml
pod "kube100-site" created
```
可以使用Kubectl命令查看Pod的状态
```
$ kubectl get pods
NAME           READY     STATUS    RESTARTS   AGE
kube100-site   2/2       Running   0          1m
```


三，创建Deployment
Kubernetes提供了一个Deployment的概念 ，目的是让Kubernetes去管理一组Pod的副本，也就是副本集 ，这样就能够保证一定数量的副本一直可用，不会因为某一个Pod挂掉导致整个服务挂掉。
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube100-site
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
        - name: flaskapp-demo
          image: jcdemo/flaskapp
          ports:
            - containerPort: 5000
```
- 注意这里apiVersion对应的值是extensions/v1beta1，同时也需要将kind的类型指定为Deployment。
- metadata指定一些meta信息，包括名字或标签之类的。
- spec 选项定义需要两个副本，此处可以设置很多属性，例如受此Deployment影响的Pod的选择器等
- spec 选项的template其实就是对Pod对象的定义

将上述的YAML文件保存为deployment.yaml，然后创建Deployment：
```
$ kubectl create -f deployment.yaml
deployment "kube100-site" created
```
可以使用如下命令检查Deployment的列表：
```
$ kubectl get deployments
NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube100-site   2         2         2            2           2m

```

另一个例子
```
#test-pod 
apiVersion: v1 #指定api版本，此值必须在kubectl apiversion中   
kind: Pod #指定创建资源的角色/类型   
metadata: #资源的元数据/属性   
  name: test-pod #资源的名字，在同一个namespace中必须唯一   
  labels: #设定资源的标签 
    k8s-app: apache   
    version: v1   
    kubernetes.io/cluster-service: "true"   
  annotations:            #自定义注解列表   
    - name: String        #自定义注解名字   
spec: #specification of the resource content 指定该资源的内容   
  restartPolicy: Always #表明该容器一直运行，默认k8s的策略，在此容器退出后，会立即创建一个相同的容器   
  nodeSelector:     #节点选择，先给主机打标签kubectl label nodes kube-node1 zone=node1   
    zone: node1   
  containers:   
  - name: test-pod #容器的名字   
    image: 10.192.21.18:5000/test/chat:latest #容器使用的镜像地址   
    imagePullPolicy: Never #三个选择Always、Never、IfNotPresent，每次启动时检查和更新（从registery）images的策略， 
                           # Always，每次都检查 
                           # Never，每次都不检查（不管本地是否有） 
                           # IfNotPresent，如果本地有就不检查，如果没有就拉取 
    command: ['sh'] #启动容器的运行命令，将覆盖容器中的Entrypoint,对应Dockefile中的ENTRYPOINT   
    args: ["$(str)"] #启动容器的命令参数，对应Dockerfile中CMD参数   
    env: #指定容器中的环境变量   
    - name: str #变量的名字   
      value: "/etc/run.sh" #变量的值   
    resources: #资源管理 
      requests: #容器运行时，最低资源需求，也就是说最少需要多少资源容器才能正常运行   
        cpu: 0.1 #CPU资源（核数），两种方式，浮点数或者是整数+m，0.1=100m，最少值为0.001核（1m） 
        memory: 32Mi #内存使用量   
      limits: #资源限制   
        cpu: 0.5   
        memory: 1000Mi   
    ports:   
    - containerPort: 80 #容器开发对外的端口 
      name: httpd  #名称 
      protocol: TCP   
    livenessProbe: #pod内容器健康检查的设置 
      httpGet: #通过httpget检查健康，返回200-399之间，则认为容器正常   
        path: / #URI地址   
        port: 80   
        #host: 127.0.0.1 #主机地址   
        scheme: HTTP   
      initialDelaySeconds: 180 #表明第一次检测在容器启动后多长时间后开始   
      timeoutSeconds: 5 #检测的超时时间   
      periodSeconds: 15  #检查间隔时间   
      #也可以用这种方法   
      #exec: 执行命令的方法进行监测，如果其退出码不为0，则认为容器正常   
      #  command:   
      #    - cat   
      #    - /tmp/health   
      #也可以用这种方法   
      #tcpSocket: //通过tcpSocket检查健康    
      #  port: number    
    lifecycle: #生命周期管理   
      postStart: #容器运行之前运行的任务   
        exec:   
          command:   
            - 'sh'   
            - 'yum upgrade -y'   
      preStop:#容器关闭之前运行的任务   
        exec:   
          command: ['service httpd stop']   
    volumeMounts:  #挂载持久存储卷 
    - name: volume #挂载设备的名字，与volumes[*].name 需要对应     
      mountPath: /data #挂载到容器的某个路径下   
      readOnly: True   
  volumes: #定义一组挂载设备   
  - name: volume #定义一个挂载设备的名字   
    #meptyDir: {}   
    hostPath:   
      path: /opt #挂载设备类型为hostPath，路径为宿主机下的/opt,这里设备类型支持很多种 
    #nfs
```

**Comment by rainit2006** [comment]
https://cstoku.dev/posts/2018/k8sdojo-08/

replicas : Podの複製数
![image](https://user-images.githubusercontent.com/12871721/72976152-5d5f8d80-3e15-11ea-9dee-8dce4f80229d.png)



selector : Label Selector。Labelを選択するための設定を指定する。selector というフィールドに指定をする。指定の仕方は2つある。
1. matchLabels
等価ベースの比較をする。 指定したLabelと全て一致したものが対象になる。
2. matchExpressions
(In, NotIn, Exists, DoesNotExists) operator を使って柔軟な選択ができる。

template : Pod Templateを指定
ReplicaSetで複製するためのPodの雛形を指定する。指定は template フィールドに指定する。
ここで注意が必要なのが、Label Selectorで指定したものが metadata.labels で指定したものと一致している必要がある。 一致してない場合はKubernetesから拒否され、作成できない。

**Comment by rainit2006** [comment]
https://cstoku.dev/posts/2018/k8sdojo-08/

Deploymentは以下の機能を提供する。
- PodのRolling Update
- Rolloutの履歴を保持
- Rollback

Deploymentは実際のところPodを直接管理しているのではなく、ReplicaSetを管理する。 Deploymentを変更した際は、新しいReplicaSetを作成してPodを置き換えていく。
![image](https://user-images.githubusercontent.com/12871721/72977141-3d30ce00-3e17-11ea-85d3-81a45a2dbc28.png)

**Comment by rainit2006** [comment]
https://zhuanlan.zhihu.com/p/105942115

# kubernetes中的CNI （Container Network Interface）
## 概念
CNI：容器网络的 API 接口。Kubelet 通过这个标准的 API 调用不同的网络插件配实现置网络
CNI 插件：一系列实现了 CNI API 接口的网络插件

##  Kubernetes 中如何使用
1. 配置 CNI 配置文件（/etc/cni/net.d/xxnet.conf）
2. 安装 CNI 二进制插件（/opt/cni/bin/xxnet）
3. 在这个节点上创建 Pod
4. Kubelet 会根据 CNI 配置文件执行 CNI 插件
5. Pod 的网络就配置完成了
![image](https://user-images.githubusercontent.com/12871721/87620645-1023ff00-c75a-11ea-9098-c2965e59c0c6.png)

## CNI 插件通常有三种模式
![image](https://user-images.githubusercontent.com/12871721/87620685-292cb000-c75a-11ea-852e-1b23591406e0.png)

## CNI插件
CNI 插件实现通常需要两个部分：
一个二进制的 CNI 插件去配置 Pod 的网卡和 IP 等 ——> 给 Pod 插上网线
一个 Daemon 进程去管理 Pod 之间的网络打通 ——> 给 Pod 连上网络，让每一个 Pod 的 IP 在集群中都能被访问到

## 如何选择CNI插件
社区那么多插件，需要如何选择？
### 1. 环境限制：
不同环境支持的底层能力不同
虚拟化 网络限制多，需要选择支持 Overlay 的插件：Flannel-vxlan，Calico-ipip，Weave 等。
物理机 选择 Underlay 或路由的插件。例如：calico-bgp，flannel-hostgw，sriov等。
公有云 如果有则选云厂商支持的。例如：Aliyun 的 Terway。
### 2. 功能需求：
不同实现支持的功能不同
安全 NetworkPolicy 支持 Pod 网络间的访问策略，Calico，Weave。
集群外资源互联互通 选择 Underlay 的网络，例如 sriov，calico-bgp。
服务发现与负载均衡 很多 Underlay 的插件不支持 K8s service 服务发现。
### 3. 性能需求：
不同实现的性能损失不同
Pod 创建速度 Overlay 或者路由模式的网络插件创建快，Underlay 模式网络插件创建慢。
Pod 网络性能 Overlay 性能相对较差，Underlay 模式和路由模式网络插件性能好。

**Comment by rainit2006** [comment]
https://cstoku.dev/posts/2018/k8sdojo-09/
## Service
ServiceはPodへの接続を解決してくれる抽象的なオブジェクトだ。端的にはSelectorで選択したPodをUpstreamとしたLBだ。
Serviceには4つの種類がある。
- ClusterIP
- NodePort
- LoadBalancer
- ExternalName

###1， ClusterIP
ClusterIPはKubernetes内での通信で利用する。クラスタ内でIPアドレスが払い出され、それを利用してPod間で通信を行う。
<image src='https://user-images.githubusercontent.com/12871721/87621955-fb953600-c75c-11ea-98d4-8e89044e21a3.png' width=250>

ports にServiceでのポートの転送設定を配列で指定する。
name : ポートの名前を指定する。DNS_LABEL に従っている必要があり、Service定義内でユニークである必要がある。また、1つ以上のポートを指定する場合 name が指定必須になる。
port : ServiceでExposeするポートを指定する。
targetPort : Serviceで転送する先のポートを指定する。またはPod内で定義されているNamedPortを指定する。指定されなかった場合、 port で指定されたポートを利用する。
protocol : port で使用するプロトコルを指定する。 TCP / UDP / SCTP を指定できる。デフォルトは TCP。

SelectorでトラフィックをルーティングするPodを選択する。
```
ports:
- name: http
  port: 80
  targetPort: 8080
  protocol: TCP

selector:
  app: nginx
  tier: frontend
```

### 2.NodePort
NodePortはKubernetesのNodeのランダムなポートを使用して外部のサーバーからの疎通性を取ってくれる。 その後はClusterIPのServiceと同様だ。
<image src='https://user-images.githubusercontent.com/12871721/87622585-5e3b0180-c75e-11ea-842f-9e86fca41061.png ' width=250>

### 3. LoadBalancer
LoadBalancerはNodePortのServiceを作成した上で、さらに外部のLoadBalanerを作成し、LoadBalancerのUpstreamとしてNodePortで疎通性を取っているポートへ転送するよう設定してくれる。
実は、 ClusterIP / NodePort / LoadBalancer はそれぞれ拡張されている形で実装されている。
<image src='https://user-images.githubusercontent.com/12871721/87622657-8cb8dc80-c75e-11ea-8780-2c6e321e376d.png' width=250>

### 4. ExternalName
ExternalNameはこれまでのServiceとは違う。ExternalNameは外部のサービスに対してのエイリアス(別名)を作成できる。
<image src='https://user-images.githubusercontent.com/12871721/87622711-a9edab00-c75e-11ea-8949-b4539f26f063.png' width=250>
