### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by rainit2006** [rainit2006/My_AWS-Cloud#5]

**Comment by rainit2006** [comment]
**AWS応用例**
- Amazon ECSの最新事例 JAWS-UG 横浜 #10
https://www.slideshare.net/AmazonWebServicesJapan/amazon-ecs-jawsug-10

**Comment by rainit2006** [comment]
http://media.amazonwebservices.com/jp/csd20140909/TA-02.pdf

*S3和EBS*
1. S3适合需要长期持久存储的内容；
2. S3容量更大(1byte到5TB，单个文件大小为5GB)，EBS最大为1TB；
3. S3文件不是存储在文件系统上，需要通过命令行访问；
4. S3可以跨EC2访问，EBS只能通过EC2访问；
5. S3比EBS便宜；
6. EBS比S3快；

S3について
•Amazon EC2上から外部のデータサーバーとしてアクセスできる。
•HTTPリクエストでどこからでもアクセス可能
Amazon S3 represents an object storage for data that deals with user files like Google Docs does it (flat file structure). 
Amazon S3 stores data as objects in a flat environment (without a hierarchy). Each object (file) in the storage contains a header with associated sequence of bytes from 0 byte to 5 TB. Objects in Amazon S3 are associated with a unique identifier (key), so access to them can be obtained through web requests from anywhere. 
As compared to Amazon EBS, the process of requesting an object in Amazon S3 is slower, but Amazon S3 is a highly scalable storage service with 99,999999999% data durability. 
 Thus, it’s better to use it to store and deliver objects that don’t require a lot of read/write operations

EBSについて
•Amazon EC2上のインスタンスからボリュームをマウントし、利用する。
「Amazon EBS」では、1GB～1TBまで1GB単位で仮想ディスクを生成することが可能です。通常利用の他にも、RAID0のように複数のボリュームを束ねて（ストライピング）使うことで高いI/Oパフォーマンスを実現させる使い方ができます。また、EBSボリュームのスナップショットを「Amazon S3」のストレージ上に保存させるようなAPIも公開されています。
Amazon EBS is an example of a block level storage similar to your desktop’s drive or virtual disk in virtualized environments.
 It’s important as once you configure the volume in Amazon EBS, it can’t be easily scaled. If you need more storage space, you will need to buy and configure a new volume of a bigger size.


考察
•EBS側に置くと良さげなデータ ◦各種ログやDBデータなど頻繁にインスタンスからアクセスするデータ
◦外からアクセスする必要の無いデータ
•S3側に置くと良さげなデータ ◦画像ファイルなどの静的ファイル系データ
◦イメージファイルなどやバックアップファイルなどファイルサイズが大きく、あまりアクセスしないもの
◦HTTP経由でアクセスできる必要があるデータ

----------------------------------
Amazon Glacierとは？
バックアップやアーカイブのために開発された、セキュアかつ堅牢性の高いストレージ
Amazon S3と同等の99.999999999%の耐久性を確保しつつ、S3の約1/3の費用で利用できる
データの取り出し命令を発行してから実際にデータを取り出せる状態になるまで、通常3~5時間の時間が必要
オンプレミス環境ではテープライブラリに保存するような、各種ログやバックアップデータなどの大容量でアクセス頻度の低いデータの長期保存に最適
S3連携機能： S3BucketにLifecycleポリシーを設定すると、一定期間が経過したファイルは自動的にGlacierに待避される

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

EC2有四种pricing方式：
1, On demand:  按小时收费
オンデマンドインスタンスでは、長期間の契約や前払いは必要なく、コンピューティング性能に対して時間あたりの料金をお支払いいただきます。
通常、EC2インスタンスを起動すればこの費用体系が適用されます。
2. リザーブドインスタンス（Reserved Instances ）
一定期間の継続利用をコミットすることで、割引を受けられる購入オプションです。
3. スポットインスタンス(Spot Instances )
起動できない or 強制終了されるリスクを負うことで、大幅にコスト削減が可能な購入方法です。
変動するスポット価格に対し、希望価格設定して入札します。入札価格がスポット価格を上回っていればインスタンスが起動しますが、スポット価格が高騰し入札価格を上回るとインスタンスは強制的に終了（Terminate）させられます。
4. Dedicated Hosts

**Comment by rainit2006** [comment]
- AWS SDK for Java
この SDK は、Amazon S3、Amazon EC2、DynamoDB など、多くの AWS サービス向けの Java API を提供するため、コーディングの複雑さが軽減されます。
https://aws.amazon.com/jp/sdk-for-java/

- AWS CLI のインストールと設定
http://docs.aws.amazon.com/ja_jp/streams/latest/dev/kinesis-tutorial-cli-installation.html

 - AWS SDK for Java を使用して Amazon EMR クラスターを作成する
http://docs.aws.amazon.com/ja_jp/emr/latest/ManagementGuide/calling-emr-with-java-sdk.html

**Comment by rainit2006** [comment]
**CloudFormation**
https://dev.classmethod.jp/beginners/chonyumon-cloudformation/
![image](https://user-images.githubusercontent.com/12871721/33813682-c33d0c7c-de68-11e7-9091-53c5ad220da2.png)

- template的说明：比如mapping
http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html

项目里利用Boto来实现cloudformation生成的程序实现。
http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html
Boto は Python のパッケージで、 Amazon S3 を含む AWS へのインターフェイスです。

-------------------------------
**CloudFormationの要素**
```
AWSTemplateFormatVersion: "version date"　#必須：2010−09−09で固定
 
Description: #任意：テンプレートの説明
  String
 
Metadata: #任意：テンプレートに関する追加情報
  template metadata
 
Parameters: #任意：テンプレートに渡すことができる値
  set of parameters
 
Mappings: #任意：条件によるキーと値のマッピング
  set of mappings
 
Conditions: #任意：条件の定義
  set of conditions
 
Transform: #任意：AWS Serverless Application Modelのバージョンを指定
  set of transforms
 
Resources:　#必須：スタックで構築するリソースを指定
  set of resources
 
Outputs:　#任意：スタックのプロパティから返される値の表示
  set of outputs
```

https://dev.classmethod.jp/cloud/aws/cloudformation-beginner01/
![image](https://user-images.githubusercontent.com/12871721/34822254-96d1e73e-f709-11e7-9380-7a585b092581.png)
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FirstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: FirstVPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: FirstVPC-IGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FirstVPC
      InternetGatewayId: !Ref InternetGateway
  FrontendRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-FrontendRoute
  FrontendRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref FrontendRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  FrontendSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-FrontendSubnet
  FrontendSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnet
      RouteTableId: !Ref FrontendRouteTable
```

- DependsOn（リソース依存関係の定義）
特定リソースが他のリソースに続けて作成されるように指定します。
上のテンプレートファイル例では、FrontendRouteTableの作成時、DependsOnで、AttachGatewayリソースに対して、依存関係を設定しています。

- Resource
リソースの名前はテンプレートの中で一意である必要があります。悲しきかな、リソースの名前は[a-zA-Z0-9]+しか使えないようです。最初、ハイフンとかアンスコを駆使した名前でテンプレートを作ってしまい、地獄を見ました。使えればいいのになぁ。あと、リソース名は大文字から始めるのが慣例のようです。
リソースの定義順は任意で構いません。CloudFormationが依存関係を計算し、適切な順番でリソースを作成してくれます。逆に言えば、リソースの作成順序を制御することはできません。

- Resource type
Type: AWS::EC2::VPC
Type: AWS::EC2::InternetGateway
Type: AWS::EC2::VPCGatewayAttachment
Type: AWS::EC2::RouteTable
Type: AWS::EC2::Route
Type: AWS::EC2::Subnet
Type: AWS::EC2::SubnetRouteTableAssociation
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html

- 組み込み関数
https://qiita.com/bisque33/items/51147a65c2ba40417d01
Fn::Join   : 指定された配列を、指定された連結文字列で結合します。
```
"Value": { "Fn::Join" : [ ",", { "Ref": "DMZSubnets" } ] }
例えば、パラメータのDMZSubnetsが["subnet-aaaaaa","subnet-bbbbbb"]だとすると、
"Value": { "Fn::Join" : [ ",", ["subnet-aaaaaa","subnet-bbbbbb"] ] }となって、
"Value": "subnet-aaaaaa,subnet-bbbbbb"になります。
```

Fn::GetAtt　　：指定されたオブジェクトから特定の属性値を取得します。

Fn::Base64　　：
EC2にミドルウェアを設定する時に環境固有の情報をパラメータから入力します。しかし日本語のようなマルチバイト文字を入力すると全て『?』と表示されてしまう。結論として、マルチバイト文字を入力する方法はありませんでした。EC2のUserDataやMetadataへ流し込む時にマルチバイトが文字化けしてしまいます。その代わり一旦ASCII文字に変換すれば、ASCII文字を入力することになるので使用できることがわかりました。CloudFormationで使用できる組み込み関数の中でASCII文字に変換できるのはFn::Base64です。Fn::Base64を使用してBase64エンコーディングしてASCII文字として入力します。
![image](https://user-images.githubusercontent.com/12871721/34860363-37f5d06c-f7a0-11e7-80bf-3b31cdd62b68.png)
https://dev.classmethod.jp/cloud/aws/cfn-multibyte-character-input/

- ランタイムの設定ができる「パラメータ」
Resourcesと並んでParametersというものを定義しています。ここに定義したパラメータは、スタック作成時に動的に指定し、各リソースのパラメータに利用することができます。Refという関数を用いて、パラメータの値を参照できるようになっています。
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters" : {
    "KeyName" : {★★
      "Description" : "Name of an existing EC2 KeyPair to enable SSH access to the web server",
      "Type" : "String"
    }
  },
  "Resources": {
(略)
    "WebServer" : {
      "Type" : "AWS::EC2::Instance",
      "Properties" : {
        "ImageId" : "ami-54cf5c3d",
        "InstanceType" : "t1.micro",
        "KeyName" : { "Ref" : "KeyName" }, ★★
        "SecurityGroupIds" : [
          { "Ref" : "SSHGroup" },
          { "Ref" : "WebGroup" }
        ]
      }
    },
(略)
  }
}
```
![image](https://user-images.githubusercontent.com/12871721/34860857-beda06fe-f7a3-11e7-9afb-e99a4989ecf7.png)

**Conditions**
定义一些条件，在Resource里可以指定某个条件，当满足这个条件时才有效。
可参考下面URL里的例子。
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
テスト環境と本稼働環境など、異なるコンテキストでリソースを作成できるテンプレートを再利用する場合に、条件を使用することがあります。テンプレートで EnvironmentType 入力パラメーターを追加できます。このパラメーターは入力として prod または test を受け取ることができます。本稼働環境では特定の機能に Amazon EC2 インスタンスを含め、テスト環境ではコスト削減のために使用する機能数を減らす場合があります。条件を使用すると、どのリソースを作成するかや、それらを各環境タイプでどのように設定するかを定義できます。

**AWS::Region**
AWS CloudFormation によって事前定義されたパラメータ(擬似パラメーター)です。テンプレートでは宣言しません。
他の疑似パラメータ：
AWS::AccountId　：　スタックが作成されているアカウントの AWS アカウント ID。
AWS::Partition、AWS::StackNameなど
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html


**スタックを作成した結果分かったことを教えて欲しい「アウトプット」**
https://dev.classmethod.jp/cloud/aws/cloudformation-firstcontact/
スタックが完成した後、CloudFormationのOutputsというタブで、この情報が確認できるようになります。
![image](https://user-images.githubusercontent.com/12871721/34861244-df953d84-f7a6-11e7-9a3a-62d04e4fd50a.png)

**cfn-init**
https://dev.classmethod.jp/cloud/aws/cfn-init/
「機能特化したAMIは作らず、プレーンなAMIにUserDataを与え、起動したら勝手に特化するように仕組む」という場面に利用。CloudFormationはcfn-initというヘルパースクリプトを用意しています。

cfn-initは、CloudFormationテンプレートのMetadataに書いた内容を読み込んで処理してくれる。
`$ cfn-init -s STACK_NAME -r Logical_ID --region REGION`
STACK_NAME | CloudFormationのスタック名
Logical ID | Resourceの名前。
REGION | リージョン
![image](https://user-images.githubusercontent.com/12871721/34861754-117f8dd8-f7aa-11e7-86bc-d78761d5492b.png)




**UserData**
UserDataに定義したスクリプトが実行されます。
httpdインストールしましょうか？
```
    "UserData" : { "Fn::Base64" : { "Fn::Join" : ["", [
      "#!/bin/bash\n",
      "yum -y update\n",
      "yum -y install httpd\n",
      "chkconfig httpd on\n",
      "service httpd start\n"
    ]]}}
```
User Dataの指定方法
"UserData" : { "Fn::Base64" : { "Fn::Join" : ["", [〜]]}}
というのはイディオムなので覚えておきましょう。
